language: objective-c

script:
- open -b com.apple.iphonesimulator # Workaround https://github.com/travis-ci/travis-ci/issues/3040
- xcodebuild test -workspace CucumberishExample/CucumberishExample.xcworkspace -scheme CucumberishTest -destination "platform=iOS Simulator,name=iPhone 6,OS=9.2"